CREATE TABLE PERSON (
PERSON_ID	INTEGER NOT NULL, 
NAME	VARCHAR(15),
PRIMARY KEY (PERSON_ID));

INSERT INTO PERSON VALUES (100, 'JOHN');
INSERT INTO PERSON VALUES (101, 'MIKE');
INSERT INTO PERSON VALUES (102, 'STEVE');
INSERT INTO PERSON VALUES (103, 'JACOB');
INSERT INTO PERSON VALUES (104, 'TY');
INSERT INTO PERSON VALUES (105, 'DANIEL');

CREATE TABLE LOCATION (
LOCATION_ID	INTEGER NOT NULL,
NAME		VARCHAR(100), 
ADDRESS		VARCHAR(100),
PRIMARY KEY (LOCATION_ID));

INSERT INTO LOCATION VALUES (100, 'Good Eats', '123 Broadway');
INSERT INTO LOCATION VALUES (101, 'Gramercy Tavern', '20th street');
INSERT INTO LOCATION VALUES (102, "Lion's Pride", '123 Goldshire');

INSERT INTO LOCATION VALUES (200, 'Brookfield Place', '521 Broadway');
INSERT INTO LOCATION VALUES (201, 'Shopping Girlfriend NYC', '230 Vesey');
INSERT INTO LOCATION VALUES (202, 'Disney Store', '39th Street');

INSERT INTO LOCATION VALUES (300, 'Majestic Theatre', 'Time Square');
INSERT INTO LOCATION VALUES (301, 'Shubert Theatre', 'Time Square');
INSERT INTO LOCATION VALUES (302, 'Karazhan Opera Hall', '671 Desolace Street');


CREATE TABLE RESTAURANT_LOCATION (
RESTAURANT_ID	INTEGER NOT NULL,
FOOD_TYPE	VARCHAR(20),
PRICE_INDICATOR VARCHAR(4),
PRIMARY KEY 	(RESTAURANT_ID),
FOREIGN KEY 	(RESTAURANT_ID) REFERENCES LOCATION (LOCATION_ID) ON DELETE CASCADE ON UPDATE CASCADE);

INSERT INTO RESTAURANT_LOCATION VALUES (100, 'AMERICAN', '$$');
INSERT INTO RESTAURANT_LOCATION VALUES (101, 'NEW AMERICAN', '$$$$');
INSERT INTO RESTAURANT_LOCATION VALUES (102, 'AZEROTHIAN', '$');

CREATE TABLE SHOP (
SHOP_ID		INTEGER NOT NULL,
TYPE		VARCHAR(20),
PRIMARY KEY 	(SHOP_ID),
FOREIGN KEY 	(SHOP_ID) REFERENCES LOCATION (LOCATION_ID) ON DELETE CASCADE ON UPDATE CASCADE);

INSERT INTO SHOP VALUES (200, 'Shopping Mall');
INSERT INTO SHOP VALUES (201, 'Clothing Store');
INSERT INTO SHOP VALUES (202, 'Toy Store');

CREATE TABLE THEATER (
THEATER_ID	INTEGER NOT NULL,
PRICE_INDICATOR VARCHAR(4),
PRIMARY KEY 	(THEATER_ID),
FOREIGN KEY 	(THEATER_ID) REFERENCES LOCATION (LOCATION_ID) ON DELETE CASCADE ON UPDATE CASCADE);

INSERT INTO THEATER VALUES (300, '$$$$');
INSERT INTO THEATER VALUES (301, '$$$$');
INSERT INTO THEATER VALUES (302, '$$');

CREATE TABLE SHOWS (
SHOW_TITLE 	VARCHAR(100) NOT NULL,
PRIMARY KEY	(SHOW_TITLE));

INSERT INTO SHOWS VALUES ('Wicked');
INSERT INTO SHOWS VALUES ('Spring Awakening');
INSERT INTO SHOWS VALUES ('Cats');
INSERT INTO SHOWS VALUES ('The Big Bad Wolf');
INSERT INTO SHOWS VALUES ('Romulo & Julianne');
INSERT INTO SHOWS VALUES ('Wizard of Oz');

CREATE TABLE THEATER_SHOW (
THEATER_ID	INTEGER NOT NULL,
SHOW_TITLE	VARCHAR(100) NOT NULL, 
DATE		DATE NOT NULL,
TIME		TIME NOT NULL,
PRIMARY KEY 	(THEATER_ID, SHOW_TITLE, DATE, TIME),
FOREIGN KEY 	(THEATER_ID) REFERENCES THEATER (THEATER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY 	(SHOW_TITLE) REFERENCES SHOWS (SHOW_TITLE) ON DELETE CASCADE ON UPDATE CASCADE);

INSERT INTO THEATER_SHOW VALUES (300, 'Cats', '2020-3-23', '07:00:00');
INSERT INTO THEATER_SHOW VALUES (301, 'Romulo & Julianne', '2020-3-24','05:00:00');
INSERT INTO THEATER_SHOW VALUES (302, 'Wizard of Oz', '2020-3-25','06:00:00');

INSERT INTO THEATER_SHOW VALUES (300, 'Cats', '2020-3-22', '08:00:00');
INSERT INTO THEATER_SHOW VALUES (301, 'Romulo & Julianne', '2020-3-23','08:00:00');
INSERT INTO THEATER_SHOW VALUES (302, 'Wizard of Oz', '2020-3-20','08:00:00');

CREATE TABLE REVIEW (
REVIEW_ID	INTEGER NOT NULL,
TEXT		VARCHAR(200),
RATING		INTEGER,
PERSON_ID	INTEGER NOT NULL,
LOCATION_ID	INTEGER NOT NULL,
SHOW_TITLE	VARCHAR(100),
PRIMARY KEY	(REVIEW_ID),
FOREIGN KEY 	(PERSON_ID) REFERENCES PERSON (PERSON_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY 	(LOCATION_ID) REFERENCES LOCATION (LOCATION_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY 	(SHOW_TITLE) REFERENCES SHOWS (SHOW_TITLE) ON DELETE CASCADE ON UPDATE CASCADE);

INSERT INTO REVIEW VALUES (1000, 'What a CATastophy of a musical', 25, 102, 300, 'Cats');
INSERT INTO REVIEW VALUES (1001, 'Poor Julianne, wait... Julianne... Romulo', 80, 101, 301, 'Romulo & Julianne'); 
INSERT INTO REVIEW VALUES (1002, 'A good play', 92, 103, 302, 'Wizard of Oz'); 
INSERT INTO REVIEW VALUES (1003, 'A PURRRfect play', 99, 104, 300, 'Cats'); 
INSERT INTO REVIEW VALUES (1004, 'Meh', 85, 105, 302, 'Wizard of Oz'); 


CREATE TABLE COMMENT (
COMMENT_ID	INT NOT NULL,
TEXT		VARCHAR(200),
REVIEW_ID	INTEGER NOT NULL,
PERSON_ID	INTEGER NOT NULL,
PRIMARY KEY	(COMMENT_ID),
FOREIGN KEY 	(PERSON_ID) REFERENCES PERSON (PERSON_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY 	(REVIEW_ID) REFERENCES REVIEW (REVIEW_ID) ON DELETE CASCADE ON UPDATE CASCADE);

INSERT INTO COMMENT VALUES (2000, 'Hey, Cats is a good play', 1000, 103);
INSERT INTO COMMENT VALUES (2001, 'Hey, Wizard of Oz is more than meh!', 1004, 103);
INSERT INTO COMMENT VALUES (2002, 'Hey, that sounds like a ripoff', 1001, 104);
