--THIS QUERY GIVES A LIST OF ALL THE LOCATION THAT ARE VERY EXPENSIVE

SELECT LOCATION.NAME, THEATER.PRICE_INDICATOR 
FROM LOCATION
INNER JOIN THEATER
ON LOCATION.LOCATION_ID = THEATER.THEATER_ID
WHERE PRICE_INDICATOR = '$$$$'
UNION
SELECT LOCATION.NAME, RESTRAURANT_LOCATION.PRICE_INDICATOR
FROM LOCATION
INNER JOIN RESTAURANT_LOCATION
ON LOCATION.LOCATION_ID = RESTAURANT_LOCATION.RESTAURANT_ID
WHERE PRICE_INDICATOR = '$$$$';

--QUERY DISPLAYS A LIST OF ALL OF THE SHOWS AND THEIR SHOW TIMES

SELECT LOCATION.NAME, THEATER_SHOW.SHOW_TITLE, THEATER_SHOW.DATE, THEATER_SHOW.TIME
FROM LOCATION
INNER JOIN THEATER_SHOW
ON LOCATION.LOCATION_ID = THEATER_SHOW.THEATER_ID

--QUERY DISPLAYS WHAT THEATER IS SHOWING WIZARD OF OZ

SELECT LOCATION.NAME, THEATER_SHOW.SHOW_TITLE, THEATER_SHOW.DATE, THEATER_SHOW.TIME
FROM LOCATION
INNER JOIN THEATER_SHOW
ON LOCATION.LOCATION_ID = THEATER_SHOW.THEATER_ID
WHERE SHOW_TITLE = 'Wizard of Oz';

--QUERY THAT DISPLAYS WHERE ALL THE TOY SHOPS ARE LOCATED

SELECT LOCATION.NAME, SHOP.TYPE, LOCATION.ADDRESS
FROM LOCATION
INNER JOIN SHOP
ON LOCATION.LOCATION_ID = SHOP_ID
WHERE TYPE = 'Toy Store';


--QUERY THAT LISTS ALL OF THE PEOPLE THAT HAVE REVIEWED WIZARD OF OZ

SELECT PERSON.NAME, REVIEW.SHOW_TITLE
FROM PERSON
INNER JOIN REVIEW 
ON REVIEW.PERSON_ID = PERSON.ID
WHERE SHOW_TITLE = 'Wizard of Oz';


--QUERY OF THE PEOPLE WHO HAVE COMMENTED ON WIZARD OF OZ REVIEWS AND THEYRE COMMENT

SELECT PERSON.NAME, REVIEW.SHOW_TITLE, COMMENT.TEXT
FROM PERSON
JOIN COMMENT 
ON COMMENT.PERSON_ID = PERSON.ID
JOIN REVIEW
ON COMMENT.REVIEW_ID = REVIEW.REVIEW_ID
WHERE SHOW_TITLE = 'Wizard of Oz';