echo Compiling source...
javac -cp .\src\com\company\DataBaseConection.java .\src\com\company\Comment.java .\src\com\company\*.java -d .\bin\
echo Starting program...
java -cp .\src\Jars\mysql-connector-java-8.0.21.jar;.\bin com.company.Main